# Generated by Django 4.1.4 on 2023-01-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('Totalfunding', models.IntegerField(blank=True, null=True)),
                ('Startup1', models.IntegerField(blank=True, null=True)),
                ('Startup2', models.IntegerField(blank=True, null=True)),
                ('Startup3', models.IntegerField(blank=True, null=True)),
                ('Startup4', models.IntegerField(blank=True, null=True)),
                ('Startup5', models.IntegerField(blank=True, null=True)),
                ('Startup6', models.IntegerField(blank=True, null=True)),
                ('Startup7', models.IntegerField(blank=True, null=True)),
                ('Startup8', models.IntegerField(blank=True, null=True)),
                ('Startup9', models.IntegerField(blank=True, null=True)),
                ('Startup10', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
