# Generated by Django 4.1.4 on 2023-01-20 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('totalbid', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='Startup1',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='Startup10',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='Startup2',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='Startup3',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='Startup4',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='Startup5',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='Startup6',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='Startup7',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='Startup8',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='Startup9',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding', models.IntegerField()),
                ('investor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttmmscoringapi.adminuser')),
                ('startup_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttmmscoringapi.startup')),
            ],
        ),
    ]
