# Generated by Django 4.1.4 on 2023-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0002_startup_remove_adminuser_startup1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='funding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='startup',
            name='totalbid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
