# Generated by Django 4.1.4 on 2023-01-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0005_startup_current_startup_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='startup',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
