# Generated by Django 4.1.4 on 2023-01-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0006_alter_adminuser_image_alter_startup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
