# Generated by Django 4.1.4 on 2023-01-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0007_alter_startup_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='finalsubmit',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
