# Generated by Django 4.1.4 on 2023-01-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0008_funding_finalsubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='finalsubmit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
