# Generated by Django 4.1.4 on 2023-01-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0009_alter_funding_finalsubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='showprogress',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
