# Generated by Django 4.1.4 on 2023-01-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0010_startup_showprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='showinvestor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
