# Generated by Django 4.1.4 on 2023-01-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0011_startup_showinvestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='isfunded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
