# Generated by Django 4.1.5 on 2023-01-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0014_portalcontrol_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalcontrol',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('0', 'beforebidding'), ('1', 'bidding'), ('2', 'afterbidding')], max_length=20, null=True),
        ),
    ]
