# Generated by Django 4.1.5 on 2023-01-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0015_alter_portalcontrol_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalcontrol',
            name='control_status',
        ),
    ]
