# Generated by Django 4.1.5 on 2023-01-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0016_remove_portalcontrol_control_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcontrol',
            name='bidding_start',
            field=models.BooleanField(default=False),
        ),
    ]
