# Generated by Django 4.1.5 on 2023-01-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0017_portalcontrol_bidding_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding', models.IntegerField(blank=True, null=True)),
                ('finalsubmit', models.BooleanField(blank=True, default=False, null=True)),
                ('investor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttmmscoringapi.adminuser')),
                ('startup_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttmmscoringapi.startup')),
            ],
        ),
    ]
