# Generated by Django 4.1.5 on 2023-01-25 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0018_funding2'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcontrol',
            name='startup_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttmmscoringapi.startup'),
        ),
    ]
