# Generated by Django 4.1.5 on 2023-01-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0019_portalcontrol_startup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portalcontrol',
            old_name='startup_name',
            new_name='current_name',
        ),
    ]
