# Generated by Django 4.1.5 on 2023-01-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0020_rename_startup_name_portalcontrol_current_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portalcontrol',
            old_name='current_name',
            new_name='current_startup',
        ),
    ]
