# Generated by Django 4.1.5 on 2023-01-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0021_rename_current_name_portalcontrol_current_startup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalcontrol',
            name='bidding_start',
        ),
    ]
