# Generated by Django 4.1.5 on 2023-01-26 06:20

from django.db import migrations, models
import ttmmscoringapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0022_remove_portalcontrol_bidding_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='image2',
            field=models.FileField(blank=True, upload_to=ttmmscoringapi.models.upload_image),
        ),
    ]
