# Generated by Django 4.1.5 on 2023-01-26 15:15

from django.db import migrations, models
import ttmmscoringapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0023_startup_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='ppt',
            field=models.FileField(blank=True, upload_to=ttmmscoringapi.models.upload_ppt),
        ),
    ]
