# Generated by Django 4.1.5 on 2023-01-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0024_startup_ppt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('0', 'beforebidding'), ('1', 'bidding'), ('2', 'afterbidding')], max_length=20)),
                ('votes', models.IntegerField(default=0)),
                ('startup_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttmmscoringapi.adminuser')),
            ],
        ),
    ]
