# Generated by Django 4.1.5 on 2023-01-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttmmscoringapi', '0026_choice_question_delete_poll_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
